sudo: required

dist: trusty

language: python

cache:
  directories:
    - gs
    - $HOME/.cache/pip
    - importer-test-files

addons:
  postgresql: "9.3"

services:
 - postgresql

matrix:
  include:
    - python: "2.7"
      env: GS_VERSION=2.7.x GDAL_DATA="/usr/local/lib/gdal/share/gdal/"
    - python: "2.7"
      env: GS_VERSION=2.8.x GDAL_DATA="/usr/local/lib/gdal/share/gdal/"
    - python: "2.7"
      env: GS_VERSION=master GDAL_DATA="/usr/local/lib/gdal/share/gdal/"


virtualenv:
  system_site_packages: true

before_install:
  - chmod +x ./scripts/install.sh
  - chmod +x ./scripts/before_script.sh

install:
  - ./scripts/install.sh

before_script:
  - sudo scripts/before_script.sh

script:
  - flake8 osgeo_importer
  - python manage.py test osgeo_importer

notifications:
  slack: prominentedge:9VnNQcaSr6mHKSC2XHwEjkam
  email:
    on_success: never
    on_failure: never
